users:
  - id: 1
    username: "ivan_ivanov"
    age: 25
    createdAt: "2023-10-01T12:00:00Z"
    following: [2, 3]
    followers: [4, 5]
  - id: 2
    username: "anna_smith"
    age: 30
    createdAt: "2023-09-15T08:30:00Z"
    following: [1]
    followers: [1, 3]